[parity]
chain = "config/demo-spec.json"
base_path = "/tmp/parity0"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[account]
password = ["config/node.pwds"]
[ui]
port = 8180
[websockets]
port = 8450
